[package]
name = "dev.peios.installer-gxwi-debuginfo"
description = "Debugging symbols for the graphical Peios installer"
license = "(((MIT OR Apache-2.0) AND Unicode-3.0) AND Apache-2.0 AND (Apache-2.0 OR BSD-2-Clause OR MIT) AND (Apache-2.0 OR BSL-1.0) AND (Apache-2.0 OR MIT) AND BSD-3-Clause AND ISC AND MIT AND (MIT AND BSD-3-Clause) AND (MIT OR Unlicense)) AND OFL-1.1"

[dependencies]
"dev.peios.installer-gxwi" = "= {{release}}"
"dev.peios.installer-gxwi-debugsource" = "= {{release}}"

[files]
"@source:LICENSE" = "usr/share/licenses/dev.peios.installer-gxwi-debuginfo/LICENSE"
":licenses/**" = "usr/share/licenses/dev.peios.installer-gxwi-debuginfo/third-party"
"@source:page/fonts/*.LICENSE" = "usr/share/licenses/dev.peios.installer-gxwi-debuginfo/fonts"
":debug/installer-gxwi/usr/lib/debug/**" = "usr/lib/debug"
